In [5]:
import pandas as pd

In [7]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 512.8 kB/s eta 0:00:00a 0:00:01
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [8]:
df = pd.read_excel('practiceData.xlsx')

In [9]:
df

             Name  Age     City
0     ajay sharma   34   mohali
1     pawan kumar   45    delhi
2     rajat singh   43  landran
3  manpreet singh   23      chd
4     lalit pawar   55    delhi
5      raja kumar   33      chd

In [14]:
df[['First_Name', 'Last_Name']] = df['Name'].str.split(' ',expand=True,n=1)

In [15]:
df

             Name  Age     City First_Name Last_Name
0     ajay sharma   34   mohali       ajay    sharma
1     pawan kumar   45    delhi      pawan     kumar
2     rajat singh   43  landran      rajat     singh
3  manpreet singh   23      chd   manpreet     singh
4     lalit pawar   55    delhi      lalit     pawar
5      raja kumar   33      chd       raja     kumar

In [17]:
df = df[['First_Name','Last_Name','Age','City']]

In [18]:
df

  First_Name Last_Name  Age     City
0       ajay    sharma   34   mohali
1      pawan     kumar   45    delhi
2      rajat     singh   43  landran
3   manpreet     singh   23      chd
4      lalit     pawar   55    delhi
5       raja     kumar   33      chd

In [19]:
def age_category(age):
    if age <18:
        return 'minor'
    elif age < 40:
        return 'working'
    elif age < 60:
        return 'senior'
    else:
        return 'retired'

In [20]:
df['Category']=df['Age'].apply(age_category)

In [21]:
df

  First_Name Last_Name  Age     City Category
0       ajay    sharma   34   mohali  working
1      pawan     kumar   45    delhi   senior
2      rajat     singh   43  landran   senior
3   manpreet     singh   23      chd  working
4      lalit     pawar   55    delhi   senior
5       raja     kumar   33      chd  working

In [26]:
df['First_Name']=df['First_Name'].str.title()

In [25]:
df

  First_Name Last_Name  Age     City Category
0       Ajay    sharma   34   mohali  working
1      Pawan     kumar   45    delhi   senior
2      Rajat     singh   43  landran   senior
3   Manpreet     singh   23      chd  working
4      Lalit     pawar   55    delhi   senior
5       Raja     kumar   33      chd  working

In [30]:
df['First_Name'].str.len()

0    4
1    5
2    5
3    8
4    5
5    4
Name: First_Name, dtype: int64

In [28]:
df

  First_Name Last_Name  Age     City Category
0       Ajay    sharma   34   mohali  working
1      Pawan     kumar   45    delhi   senior
2      Rajat     singh   43  landran   senior
3   Manpreet     singh   23      chd  working
4      Lalit     pawar   55    delhi   senior
5       Raja     kumar   33      chd  working