In [106]:
import pandas as pd

In [107]:
df = pd.read_csv("large_messy_dataset_option2.csv")

In [108]:
df.head()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15

In [109]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    str
 2   Age          225 non-null    float64
 3   Salary       227 non-null    str
 4   City         251 non-null    str
 5   Email        300 non-null    str
 6   JoiningDate  234 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 16.5 KB

In [110]:
df.tail()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [111]:
df.describe()

       CustomerID         Age
count  300.000000  225.000000
mean   114.746667   10.746667
std     80.658385   19.774009
min      0.000000   -3.000000
25%     45.750000   -3.000000
50%    101.000000    0.000000
75%    156.250000   25.000000
max    299.000000   59.000000

In [112]:
df.isnull().sum()

CustomerID      0
Name            0
Age            75
Salary         73
City           49
Email           0
JoiningDate    66
dtype: int64

In [113]:
df['Salary']=pd.to_numeric(df['Salary'],errors='coerce')
# 'coerce' means replace invalid values with NaN (Not a Number).

In [114]:
df.head(10)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530.0,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,-3.0,NaN,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,0.0,NaN,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,-3.0,-10000.0,Bangalore,priya42@gmail.com,March 10 2023
8,35,raj,0.0,-10000.0,Chandigarh,raj15@gmail.com,2023-01-15
9,119,Aman,0.0,98172.0,Bangalore,aman25@gmail.com,2023/04/20

In [115]:
df['Salary']=abs(df['Salary'])

In [116]:
df.head(8)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530.0,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,-3.0,NaN,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,0.0,NaN,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,-3.0,10000.0,Bangalore,priya42@gmail.com,March 10 2023

In [117]:
df.describe()

       CustomerID         Age         Salary
count  300.000000  225.000000     152.000000
mean   114.746667   10.746667   38273.750000
std     80.658385   19.774009   36837.249772
min      0.000000   -3.000000   10000.000000
25%     45.750000   -3.000000   10000.000000
50%    101.000000    0.000000   10000.000000
75%    156.250000   25.000000   66370.000000
max    299.000000   59.000000  119613.000000

In [118]:
df['Salary'].isnull().sum()

np.int64(148)

In [119]:
df['Salary'].mean()

np.float64(38273.75)

In [120]:
df['Salary'].median()

np.float64(10000.0)

In [121]:
df['Salary'].mode()

0    10000.0
Name: Salary, dtype: float64

In [122]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())

In [123]:
df.head(8)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530.00,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,38273.75,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,10000.00,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,10000.00,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349.00,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,-3.0,38273.75,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,0.0,38273.75,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,-3.0,10000.00,Bangalore,priya42@gmail.com,March 10 2023

In [124]:
df['Salary'].mean()

np.float64(38273.75)

In [125]:
df['Salary'].median()

np.float64(38273.75)

In [126]:
df['Salary'].mode()

0    38273.75
Name: Salary, dtype: float64

In [127]:
df.describe()

       CustomerID         Age         Salary
count  300.000000  225.000000     300.000000
mean   114.746667   10.746667   38273.750000
std     80.658385   19.774009   26178.217897
min      0.000000   -3.000000   10000.000000
25%     45.750000   -3.000000   10000.000000
50%    101.000000    0.000000   38273.750000
75%    156.250000   25.000000   38273.750000
max    299.000000   59.000000  119613.000000

In [128]:
df[(df['Salary'] > 10000) & (df['Salary'] <=30000)]

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
120,120,Aman,0.0,24929.0,Chandigarh,aman19@gmail.com,2023/04/20
161,120,Rohit,-3.0,26377.0,Chandigarh,rohit32@gmail.com,2023/04/20
277,35,Simran,0.0,27992.0,Chandigarh,simran25@gmail.com,15/02/2023
283,283,Simran,-3.0,27806.0,Mumbai,simran38@gmail.com,2023/04/20

In [129]:
df['Salary'].value_counts()[lambda x : x>1]

Salary
38273.75    148
10000.00     86
Name: count, dtype: int64

In [130]:
df['Age'].isnull().sum()

np.int64(75)

In [131]:
df['Age'] = abs(df['Age'])

In [132]:
df.head(20)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530.00,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,38273.75,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,10000.00,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,3.0,10000.00,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349.00,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,3.0,38273.75,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,0.0,38273.75,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,3.0,10000.00,Bangalore,priya42@gmail.com,March 10 2023
8,35,raj,0.0,10000.00,Chandigarh,raj15@gmail.com,2023-01-15
9,119,Aman,0.0,98172.00,Bangalore,aman25@gmail.com,2023/04/20
10,10,Aman,3.0,38273.75,Delhi,aman19@gmail.com,NaN
11,11,Aman,NaN,86542.00,NaN,aman20@gmail.com,15/02/2023
12,28,Priya,51.0,38273.75,Bangalore,priya2@gmail.com,March 10 2023
13,13,simran,23.0,10000.00,Delhi,simran49@gmail.com,15/02/2023
14,102,Anjali,0.0,38273.75,NaN,anjali20@gmail.com,NaN
15,15,anjali,39.0,38273.75,Kolkata,anjali15@gmail.com,2023-01-15
16,16,simran,39.0,38273.75,Chandigarh,simran43@gmail.com,2023/04/20
17,17,Raj,0.0,10000.00,Bangalore,raj13@gmail.com,NaN
18,18,Priya,21.0,10000.00,NaN,priya22@gmail.com,15/02/2023
19,19,Simran,3.0,38273.75,Delhi,simran29@gmail.com,2023-01-15

In [133]:
age_mean=df.loc[df['Age']>21,'Age'].mean()
age_mean

np.float64(40.203125)

In [134]:
df.loc[df['Age'] <21,'Age']=age_mean

In [135]:
df.head(10)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530.00,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.000000,38273.75,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,10000.00,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,40.203125,10000.00,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349.00,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,40.203125,38273.75,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,40.203125,38273.75,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,40.203125,10000.00,Bangalore,priya42@gmail.com,March 10 2023
8,35,raj,40.203125,10000.00,Chandigarh,raj15@gmail.com,2023-01-15
9,119,Aman,40.203125,98172.00,Bangalore,aman25@gmail.com,2023/04/20

In [136]:
df['Age'].mean()

np.float64(40.03243055555556)

In [137]:
df['Age']=df['Age'].fillna(age_mean)

In [138]:
df.head()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,40.203125,116530.00,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.000000,38273.75,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,40.203125,10000.00,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,40.203125,10000.00,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,40.203125,112349.00,Delhi,karan43@gmail.com,2023-01-15

In [139]:
df['Age']=df['Age'].round()

In [140]:
df['Age']=df['Age'].astype(int)

In [141]:
df.head(10)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,40,116530.00,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32,38273.75,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,40,10000.00,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,40,10000.00,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,40,112349.00,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,40,38273.75,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,40,38273.75,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,40,10000.00,Bangalore,priya42@gmail.com,March 10 2023
8,35,raj,40,10000.00,Chandigarh,raj15@gmail.com,2023-01-15
9,119,Aman,40,98172.00,Bangalore,aman25@gmail.com,2023/04/20

In [142]:
df.tail()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
295,11,karan,40,38273.75,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54,39808.00,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,40,10000.00,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,40,10000.00,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,40,38273.75,Kolkata,aman17@gmail.com,2023-01-15

In [143]:
df['Age'].value_counts()[lambda x : x >1]

Age
40    235
59      6
23      5
35      5
39      4
37      4
41      4
27      3
57      3
51      2
21      2
33      2
34      2
49      2
36      2
48      2
Name: count, dtype: int64

In [144]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    str
 2   Age          300 non-null    int64
 3   Salary       300 non-null    float64
 4   City         251 non-null    str
 5   Email        300 non-null    str
 6   JoiningDate  234 non-null    str
dtypes: float64(1), int64(2), str(4)
memory usage: 16.5 KB

In [145]:
df.insert(0,"Serial_no",range(1,len(df)+1))

In [146]:
df['City'].isnull().sum()

np.int64(49)

In [147]:
missing_cities=df[df['City'].isna()]

In [148]:
df.dropna(subset=['City'],inplace=True)

In [149]:
df.info()

<class 'pandas.DataFrame'>
Index: 251 entries, 2 to 299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Serial_no    251 non-null    int64
 1   CustomerID   251 non-null    int64
 2   Name         251 non-null    str
 3   Age          251 non-null    int64
 4   Salary       251 non-null    float64
 5   City         251 non-null    str
 6   Email        251 non-null    str
 7   JoiningDate  196 non-null    str
dtypes: float64(1), int64(3), str(4)
memory usage: 17.6 KB

In [150]:
df['CustomerID'].value_counts()[lambda x : x >1]

CustomerID
35     5
28     4
135    4
58     3
10     3
13     3
20     3
27     3
80     3
99     3
61     3
38     3
77     3
76     3
143    3
146    3
121    3
128    3
3      2
21     2
22     2
107    2
25     2
67     2
49     2
132    2
44     2
87     2
148    2
59     2
150    2
109    2
65     2
69     2
74     2
91     2
127    2
33     2
31     2
93     2
138    2
97     2
100    2
144    2
40     2
112    2
37     2
120    2
36     2
123    2
139    2
113    2
103    2
101    2
Name: count, dtype: int64

In [151]:
missing_cities

,Serial_no,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.00,NaN,riya48@gmail.com,2023/04/20
1,2,139,rohit,32,38273.75,NaN,rohit42@gmail.com,15/02/2023
6,7,6,Raj,40,38273.75,NaN,raj21@gmail.com,2023-01-15
11,12,11,Aman,40,86542.00,NaN,aman20@gmail.com,15/02/2023
14,15,102,Anjali,40,38273.75,NaN,anjali20@gmail.com,NaN
18,19,18,Priya,21,10000.00,NaN,priya22@gmail.com,15/02/2023
26,27,34,Karan,59,38273.75,NaN,karan7@gmail.com,2023-01-15
33,34,33,Karan,40,10000.00,NaN,karan35@gmail.com,2023-01-15
36,37,129,rohit,40,106951.00,NaN,rohit20@gmail.com,NaN
37,38,44,Priya,40,10000.00,NaN,priya48@gmail.com,NaN
39,40,39,riya,40,38273.75,NaN,riya20@gmail.com,15/02/2023
40,41,49,aman,57,10000.00,NaN,aman37@gmail.com,NaN
43,44,133,Anjali,40,38273.75,NaN,anjali18@gmail.com,15/02/2023
47,48,47,Simran,49,38273.75,NaN,simran44@gmail.com,NaN
53,54,17,Riya,40,10000.00,NaN,riya24@gmail.com,2023-01-15
71,72,73,Priya,40,10000.00,NaN,priya32@gmail.com,2023/04/20
72,73,118,Aman,38,72976.00,NaN,aman35@gmail.com,2023-01-15
82,83,82,Simran,24,38273.75,NaN,simran20@gmail.com,March 10 2023
88,89,10,priya,40,102345.00,NaN,priya42@gmail.com,NaN
95,96,55,Raj,40,56666.00,NaN,raj24@gmail.com,NaN
101,102,125,Karan,40,10000.00,NaN,karan7@gmail.com,2023-01-15
104,105,104,Rohit,40,38273.75,NaN,rohit31@gmail.com,2023-01-15
115,116,22,karan,40,10000.00,NaN,karan24@gmail.com,2023-01-15
123,124,123,Raj,40,64350.00,NaN,raj42@gmail.com,March 10 2023
125,126,125,rohit,40,10000.00,NaN,rohit22@gmail.com,NaN
137,138,137,Aman,40,38273.75,NaN,aman2@gmail.com,March 10 2023
140,141,73,Karan,40,53202.00,NaN,karan13@gmail.com,2023-01-15
149,150,140,Raj,40,38273.75,NaN,raj5@gmail.com,March 10 2023
154,155,154,Priya,36,38273.75,NaN,priya36@gmail.com,March 10 2023
156,157,156,Karan,44,38273.75,NaN,karan20@gmail.com,NaN
170,171,67,Rohit,40,38273.75,NaN,rohit50@gmail.com,15/02/2023
171,172,125,simran,40,38273.75,NaN,simran46@gmail.com,NaN
174,175,174,karan,40,51779.00,NaN,karan34@gmail.com,2023-01-15
181,182,181,Anjali,37,38273.75,NaN,anjali16@gmail.com,NaN
185,186,185,raj,46,38273.75,NaN,raj38@gmail.com,2023/04/20
189,190,189,Raj,40,38273.75,NaN,raj15@gmail.com,March 10 2023
193,194,56,Priya,40,38273.75,NaN,priya34@gmail.com,March 10 2023
198,199,198,Simran,40,44906.00,NaN,simran49@gmail.com,2023/04/20
223,224,223,Aman,52,38273.75,NaN,aman43@gmail.com,2023/04/20
229,230,50,Rohit,40,71849.00,NaN,rohit40@gmail.com,2023/04/20
243,244,117,Karan,40,62898.00,NaN,karan6@gmail.com,2023-01-15
247,248,59,Priya,40,38273.75,NaN,priya45@gmail.com,2023-01-15
250,251,38,raj,40,38273.75,NaN,raj14@gmail.com,2023/04/20
252,253,252,Priya,59,38273.75,NaN,priya2@gmail.com,2023/04/20
257,258,257,Priya,59,10000.00,NaN,priya16@gmail.com,2023-01-15
259,260,259,Anjali,40,38273.75,NaN,anjali50@gmail.com,2023-01-15
272,273,272,priya,40,87300.00,NaN,priya20@gmail.com,2023-01-15
291,292,291,rohit,40,10000.00,NaN,rohit2@gmail.com,2023/04/20
292,293,292,rohit,40,38273.75,NaN,rohit19@gmail.com,2023-01-15

In [156]:
def missingCity():
    inputSerialNo= int(input("Enter serial no"))
    city = input("Enter city")
    mask = ((missing_cities['Serial_no'] == inputSerialNo) & (missing_cities['City'].isna()))
    if mask.any():
        missing_cities.loc[mask,'City'] = city
        print("City updated successfully")
    else:
        print("City already exists or invalid serial no ")
       
missingCity()

Enter serial no 1
Enter city cha

City already exists or invalid serial no

In [157]:
missing_cities.head(10)

,Serial_no,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.00,Chandigarh,riya48@gmail.com,2023/04/20
1,2,139,rohit,32,38273.75,NaN,rohit42@gmail.com,15/02/2023
6,7,6,Raj,40,38273.75,NaN,raj21@gmail.com,2023-01-15
11,12,11,Aman,40,86542.00,NaN,aman20@gmail.com,15/02/2023
14,15,102,Anjali,40,38273.75,NaN,anjali20@gmail.com,NaN
18,19,18,Priya,21,10000.00,NaN,priya22@gmail.com,15/02/2023
26,27,34,Karan,59,38273.75,NaN,karan7@gmail.com,2023-01-15
33,34,33,Karan,40,10000.00,NaN,karan35@gmail.com,2023-01-15
36,37,129,rohit,40,106951.00,NaN,rohit20@gmail.com,NaN
37,38,44,Priya,40,10000.00,NaN,priya48@gmail.com,NaN