In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("large_messy_dataset_option2.csv")

In [9]:
df

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    str
 2   Age          225 non-null    float64
 3   Salary       227 non-null    str
 4   City         251 non-null    str
 5   Email        300 non-null    str
 6   JoiningDate  234 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 16.5 KB

In [11]:
# Age cleaning

In [12]:
df['Age']=df['Age'].abs()

In [13]:
df.loc[df['Age'] !=0 ,'Age'].mean()

np.float64(19.767123287671232)

In [14]:
df.describe()

       CustomerID         Age
count  300.000000  225.000000
mean   114.746667   12.826667
std     80.658385   18.486752
min      0.000000    0.000000
25%     45.750000    0.000000
50%    101.000000    3.000000
75%    156.250000   25.000000
max    299.000000   59.000000

In [15]:
df.head(8)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,3.0,Not Available,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,0.0,NaN,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,3.0,-10000,Bangalore,priya42@gmail.com,March 10 2023

In [16]:
mean_age = df.loc[df['Age'] > 20 , 'Age'].mean()
mean_age

np.float64(39.621212121212125)

In [17]:
df.loc[df['Age'] < 20 ,'Age']= mean_age

In [18]:
df.head(8)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.000000,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,39.621212,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,39.621212,Not Available,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,39.621212,NaN,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,39.621212,-10000,Bangalore,priya42@gmail.com,March 10 2023

In [19]:
df['Age'].isnull().sum()

np.int64(75)

In [20]:
df['Age']=df['Age'].fillna(mean_age)

In [21]:
df['Age'].mean()

np.float64(39.62121212121212)

In [22]:
df.head()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,39.621212,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.000000,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,39.621212,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,39.621212,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,39.621212,112349,Delhi,karan43@gmail.com,2023-01-15

In [23]:
df.tail()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
295,11,karan,39.621212,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.000000,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,39.621212,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,39.621212,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,39.621212,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [24]:
df['Age'].mean()

np.float64(39.62121212121212)

In [25]:
df['Age'].median()

np.float64(39.621212121212125)

In [26]:
df['Age'].mode()

0    39.621212
Name: Age, dtype: float64

In [27]:
df['Age']=df['Age'].round()

In [28]:
df['Age']=df['Age'].astype(int)

In [29]:
df

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,40,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,40,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,40,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,40,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,40,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,40,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,40,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,40,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [30]:
# Salary Cleaning

In [31]:
df['Salary'].isnull().sum()

np.int64(73)

In [32]:
df['Salary']=pd.to_numeric(df['Salary'],errors='coerce')

In [33]:
df['Salary']=df['Salary'].abs()

In [34]:
df.head(10)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,40,116530.0,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,40,10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,40,NaN,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,40,NaN,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,March 10 2023
8,35,raj,40,10000.0,Chandigarh,raj15@gmail.com,2023-01-15
9,119,Aman,40,98172.0,Bangalore,aman25@gmail.com,2023/04/20

In [35]:
df['Salary'].isnull().sum()

np.int64(148)

In [36]:
df['Salary'].mean()

np.float64(38273.75)

In [37]:
df['Salary'].mode()

0    10000.0
Name: Salary, dtype: float64

In [38]:
df['Salary'].median()

np.float64(10000.0)

In [39]:
df['Salary']=df['Salary'].fillna(df['Salary'].mode()[0])

In [40]:
df.head(8)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,40,116530.0,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32,10000.0,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,40,10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,40,10000.0,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,40,10000.0,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,March 10 2023

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    str
 2   Age          300 non-null    int64
 3   Salary       300 non-null    float64
 4   City         251 non-null    str
 5   Email        300 non-null    str
 6   JoiningDate  234 non-null    str
dtypes: float64(1), int64(2), str(4)
memory usage: 16.5 KB

In [42]:
df.describe()

       CustomerID         Age         Salary
count  300.000000  300.000000     300.000000
mean   114.746667   39.916667   24325.366667
std     80.658385    5.357743   29762.108089
min      0.000000   21.000000   10000.000000
25%     45.750000   40.000000   10000.000000
50%    101.000000   40.000000   10000.000000
75%    156.250000   40.000000   10000.000000
max    299.000000   59.000000  119613.000000

In [43]:
# City Cleaning

In [44]:
df.head(10)

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,40,116530.0,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32,10000.0,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,40,10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,5,Simran,40,10000.0,Chandigarh,simran14@gmail.com,2023/04/20
6,6,Raj,40,10000.0,NaN,raj21@gmail.com,2023-01-15
7,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,March 10 2023
8,35,raj,40,10000.0,Chandigarh,raj15@gmail.com,2023-01-15
9,119,Aman,40,98172.0,Bangalore,aman25@gmail.com,2023/04/20

In [45]:
df['City'].isnull().sum()

np.int64(49)

In [46]:
df['Email'].is_unique

False

In [47]:
df['CustomerID'].is_unique

False

In [48]:
df

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,40,116530.0,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32,10000.0,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,40,10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,40,10000.0,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54,39808.0,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,40,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,40,10000.0,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,40,10000.0,Kolkata,aman17@gmail.com,2023-01-15

In [49]:
# insert unique column to identify
df.insert(0,"Unique_id",range(1,len(df)+1))

In [50]:
df

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.0,NaN,riya48@gmail.com,2023/04/20
1,2,139,rohit,32,10000.0,NaN,rohit42@gmail.com,15/02/2023
2,3,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,3,riya,40,10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,5,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...,...
295,296,11,karan,40,10000.0,Mumbai,karan29@gmail.com,NaN
296,297,88,anjali,54,39808.0,Delhi,anjali43@gmail.com,2023/04/20
297,298,121,Simran,40,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,299,298,Rohit,40,10000.0,Mumbai,rohit11@gmail.com,15/02/2023
299,300,299,Aman,40,10000.0,Kolkata,aman17@gmail.com,2023-01-15

In [51]:
df['City'].isna()

0       True
1       True
2      False
3      False
4      False
       ...
295    False
296    False
297    False
298    False
299    False
Name: City, Length: 300, dtype: bool

In [52]:
# Missing city data frame can be corrected later
df_missing_city = df[df['City'].isna()]

In [53]:
df_missing_city

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.0,NaN,riya48@gmail.com,2023/04/20
1,2,139,rohit,32,10000.0,NaN,rohit42@gmail.com,15/02/2023
6,7,6,Raj,40,10000.0,NaN,raj21@gmail.com,2023-01-15
11,12,11,Aman,40,86542.0,NaN,aman20@gmail.com,15/02/2023
14,15,102,Anjali,40,10000.0,NaN,anjali20@gmail.com,NaN
18,19,18,Priya,21,10000.0,NaN,priya22@gmail.com,15/02/2023
26,27,34,Karan,59,10000.0,NaN,karan7@gmail.com,2023-01-15
33,34,33,Karan,40,10000.0,NaN,karan35@gmail.com,2023-01-15
36,37,129,rohit,40,106951.0,NaN,rohit20@gmail.com,NaN
37,38,44,Priya,40,10000.0,NaN,priya48@gmail.com,NaN
39,40,39,riya,40,10000.0,NaN,riya20@gmail.com,15/02/2023
40,41,49,aman,57,10000.0,NaN,aman37@gmail.com,NaN
43,44,133,Anjali,40,10000.0,NaN,anjali18@gmail.com,15/02/2023
47,48,47,Simran,49,10000.0,NaN,simran44@gmail.com,NaN
53,54,17,Riya,40,10000.0,NaN,riya24@gmail.com,2023-01-15
71,72,73,Priya,40,10000.0,NaN,priya32@gmail.com,2023/04/20
72,73,118,Aman,38,72976.0,NaN,aman35@gmail.com,2023-01-15
82,83,82,Simran,24,10000.0,NaN,simran20@gmail.com,March 10 2023
88,89,10,priya,40,102345.0,NaN,priya42@gmail.com,NaN
95,96,55,Raj,40,56666.0,NaN,raj24@gmail.com,NaN
101,102,125,Karan,40,10000.0,NaN,karan7@gmail.com,2023-01-15
104,105,104,Rohit,40,10000.0,NaN,rohit31@gmail.com,2023-01-15
115,116,22,karan,40,10000.0,NaN,karan24@gmail.com,2023-01-15
123,124,123,Raj,40,64350.0,NaN,raj42@gmail.com,March 10 2023
125,126,125,rohit,40,10000.0,NaN,rohit22@gmail.com,NaN
137,138,137,Aman,40,10000.0,NaN,aman2@gmail.com,March 10 2023
140,141,73,Karan,40,53202.0,NaN,karan13@gmail.com,2023-01-15
149,150,140,Raj,40,10000.0,NaN,raj5@gmail.com,March 10 2023
154,155,154,Priya,36,10000.0,NaN,priya36@gmail.com,March 10 2023
156,157,156,Karan,44,10000.0,NaN,karan20@gmail.com,NaN
170,171,67,Rohit,40,10000.0,NaN,rohit50@gmail.com,15/02/2023
171,172,125,simran,40,10000.0,NaN,simran46@gmail.com,NaN
174,175,174,karan,40,51779.0,NaN,karan34@gmail.com,2023-01-15
181,182,181,Anjali,37,10000.0,NaN,anjali16@gmail.com,NaN
185,186,185,raj,46,10000.0,NaN,raj38@gmail.com,2023/04/20
189,190,189,Raj,40,10000.0,NaN,raj15@gmail.com,March 10 2023
193,194,56,Priya,40,10000.0,NaN,priya34@gmail.com,March 10 2023
198,199,198,Simran,40,44906.0,NaN,simran49@gmail.com,2023/04/20
223,224,223,Aman,52,10000.0,NaN,aman43@gmail.com,2023/04/20
229,230,50,Rohit,40,71849.0,NaN,rohit40@gmail.com,2023/04/20
243,244,117,Karan,40,62898.0,NaN,karan6@gmail.com,2023-01-15
247,248,59,Priya,40,10000.0,NaN,priya45@gmail.com,2023-01-15
250,251,38,raj,40,10000.0,NaN,raj14@gmail.com,2023/04/20
252,253,252,Priya,59,10000.0,NaN,priya2@gmail.com,2023/04/20
257,258,257,Priya,59,10000.0,NaN,priya16@gmail.com,2023-01-15
259,260,259,Anjali,40,10000.0,NaN,anjali50@gmail.com,2023-01-15
272,273,272,priya,40,87300.0,NaN,priya20@gmail.com,2023-01-15
291,292,291,rohit,40,10000.0,NaN,rohit2@gmail.com,2023/04/20
292,293,292,rohit,40,10000.0,NaN,rohit19@gmail.com,2023-01-15

In [54]:
df.dropna(subset=['City'],inplace=True)

In [55]:
df

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
2,3,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,3,riya,40,10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,5,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,6,5,Simran,40,10000.0,Chandigarh,simran14@gmail.com,2023/04/20
7,8,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,March 10 2023
...,...,...,...,...,...,...,...,...
295,296,11,karan,40,10000.0,Mumbai,karan29@gmail.com,NaN
296,297,88,anjali,54,39808.0,Delhi,anjali43@gmail.com,2023/04/20
297,298,121,Simran,40,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,299,298,Rohit,40,10000.0,Mumbai,rohit11@gmail.com,15/02/2023
299,300,299,Aman,40,10000.0,Kolkata,aman17@gmail.com,2023-01-15

In [56]:
df.info()

<class 'pandas.DataFrame'>
Index: 251 entries, 2 to 299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unique_id    251 non-null    int64
 1   CustomerID   251 non-null    int64
 2   Name         251 non-null    str
 3   Age          251 non-null    int64
 4   Salary       251 non-null    float64
 5   City         251 non-null    str
 6   Email        251 non-null    str
 7   JoiningDate  196 non-null    str
dtypes: float64(1), int64(3), str(4)
memory usage: 17.6 KB

In [57]:
df['CustomerID'].value_counts()[lambda x: x >1]

CustomerID
35     5
28     4
135    4
58     3
10     3
13     3
20     3
27     3
80     3
99     3
61     3
38     3
77     3
76     3
143    3
146    3
121    3
128    3
3      2
21     2
22     2
107    2
25     2
67     2
49     2
132    2
44     2
87     2
148    2
59     2
150    2
109    2
65     2
69     2
74     2
91     2
127    2
33     2
31     2
93     2
138    2
97     2
100    2
144    2
40     2
112    2
37     2
120    2
36     2
123    2
139    2
113    2
103    2
101    2
Name: count, dtype: int64

In [58]:
df[df['CustomerID'].duplicated()]

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
28,29,28,aman,35,10000.0,Mumbai,aman41@gmail.com,NaN
29,30,10,Rohit,27,10000.0,Bangalore,rohit9@gmail.com,March 10 2023
35,36,35,Riya,34,10000.0,Delhi,riya34@gmail.com,March 10 2023
49,50,49,Rohit,40,10000.0,Chandigarh,rohit6@gmail.com,2023/04/20
61,62,13,simran,37,10000.0,Chandigarh,simran3@gmail.com,15/02/2023
...,...,...,...,...,...,...,...,...
280,281,99,Simran,40,54934.0,Mumbai,simran37@gmail.com,15/02/2023
289,290,25,Anjali,40,10000.0,Kolkata,anjali25@gmail.com,2023/04/20
293,294,22,Aman,40,10000.0,Delhi,aman28@gmail.com,2023/04/20
294,295,101,anjali,40,10000.0,Delhi,anjali20@gmail.com,NaN
297,298,121,Simran,40,10000.0,Kolkata,simran16@gmail.com,2023-01-15

In [59]:
# name cleaning

In [60]:
df['Name']=df['Name'].str.title()

In [61]:
# city name to title case

In [62]:
df["City"]=df['City'].str.title()

In [63]:
df.head(10)

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
2,3,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,3,Riya,40,10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,5,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,6,5,Simran,40,10000.0,Chandigarh,simran14@gmail.com,2023/04/20
7,8,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,March 10 2023
8,9,35,Raj,40,10000.0,Chandigarh,raj15@gmail.com,2023-01-15
9,10,119,Aman,40,98172.0,Bangalore,aman25@gmail.com,2023/04/20
10,11,10,Aman,40,10000.0,Delhi,aman19@gmail.com,NaN
12,13,28,Priya,51,10000.0,Bangalore,priya2@gmail.com,March 10 2023
13,14,13,Simran,23,10000.0,Delhi,simran49@gmail.com,15/02/2023

In [64]:
df.describe()

        Unique_id  CustomerID         Age         Salary
count  251.000000  251.000000  251.000000     251.000000
mean   154.219124  114.904382   39.689243   23742.294821
std     85.959268   80.518264    4.980667   29485.679203
min      3.000000    2.000000   21.000000   10000.000000
25%     80.500000   45.500000   40.000000   10000.000000
50%    154.000000  100.000000   40.000000   10000.000000
75%    227.500000  156.000000   40.000000   10000.000000
max    300.000000  299.000000   59.000000  119613.000000

In [65]:
df.info()

<class 'pandas.DataFrame'>
Index: 251 entries, 2 to 299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unique_id    251 non-null    int64
 1   CustomerID   251 non-null    int64
 2   Name         251 non-null    str
 3   Age          251 non-null    int64
 4   Salary       251 non-null    float64
 5   City         251 non-null    str
 6   Email        251 non-null    str
 7   JoiningDate  196 non-null    str
dtypes: float64(1), int64(3), str(4)
memory usage: 17.6 KB

In [66]:
# date cleaning

In [67]:
df['JoiningDate'].isnull().sum()

np.int64(55)

In [68]:
df['JoiningDate'].dtype

In [69]:
df['JoiningDate'].unique

<bound method Series.unique of 2      March 10 2023
3         2023/04/20
4         2023-01-15
5         2023/04/20
7      March 10 2023
           ...
295              NaN
296       2023/04/20
297       2023-01-15
298       15/02/2023
299       2023-01-15
Name: JoiningDate, Length: 251, dtype: str>

In [70]:
df['JoiningDate']=pd.to_datetime(df['JoiningDate'],format='mixed',dayfirst=True,errors="coerce")

In [71]:
for val in df['JoiningDate'].head(15):
    print(repr(val))
# repr() shows the exact raw representation of a value.

Timestamp('2023-03-10 00:00:00')
Timestamp('2023-04-20 00:00:00')
Timestamp('2023-01-15 00:00:00')
Timestamp('2023-04-20 00:00:00')
Timestamp('2023-03-10 00:00:00')
Timestamp('2023-01-15 00:00:00')
Timestamp('2023-04-20 00:00:00')
NaT
Timestamp('2023-03-10 00:00:00')
Timestamp('2023-02-15 00:00:00')
Timestamp('2023-01-15 00:00:00')
Timestamp('2023-04-20 00:00:00')
NaT
Timestamp('2023-01-15 00:00:00')
Timestamp('2023-02-15 00:00:00')

In [72]:
df['JoiningDate'].isnull().sum()

np.int64(55)

In [73]:
df.dropna(subset="JoiningDate",inplace=True)

In [74]:
df.info()

<class 'pandas.DataFrame'>
Index: 196 entries, 2 to 299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unique_id    196 non-null    int64
 1   CustomerID   196 non-null    int64
 2   Name         196 non-null    str
 3   Age          196 non-null    int64
 4   Salary       196 non-null    float64
 5   City         196 non-null    str
 6   Email        196 non-null    str
 7   JoiningDate  196 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 13.8 KB

In [75]:
df

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
2,3,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,2023-03-10
3,4,3,Riya,40,10000.0,Kolkata,riya8@gmail.com,2023-04-20
4,5,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,6,5,Simran,40,10000.0,Chandigarh,simran14@gmail.com,2023-04-20
7,8,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,2023-03-10
...,...,...,...,...,...,...,...,...
293,294,22,Aman,40,10000.0,Delhi,aman28@gmail.com,2023-04-20
296,297,88,Anjali,54,39808.0,Delhi,anjali43@gmail.com,2023-04-20
297,298,121,Simran,40,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,299,298,Rohit,40,10000.0,Mumbai,rohit11@gmail.com,2023-02-15
299,300,299,Aman,40,10000.0,Kolkata,aman17@gmail.com,2023-01-15

In [76]:
df.describe()

,Unique_id,CustomerID,Age,Salary,JoiningDate
count,196.000000,196.000000,196.000000,196.000000,196
mean,150.357143,109.923469,39.780612,24166.224490,2023-03-03 05:23:15.918367
min,3.000000,2.000000,22.000000,10000.000000,2023-01-15 00:00:00
25%,78.500000,43.750000,40.000000,10000.000000,2023-02-15 00:00:00
50%,152.500000,96.500000,40.000000,10000.000000,2023-03-10 00:00:00
75%,223.500000,144.000000,40.000000,10000.000000,2023-04-20 00:00:00
max,300.000000,299.000000,59.000000,119613.000000,2023-04-20 00:00:00
std,86.483821,78.704441,4.920687,30040.126146,NaN

In [77]:
df

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
2,3,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,2023-03-10
3,4,3,Riya,40,10000.0,Kolkata,riya8@gmail.com,2023-04-20
4,5,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,6,5,Simran,40,10000.0,Chandigarh,simran14@gmail.com,2023-04-20
7,8,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,2023-03-10
...,...,...,...,...,...,...,...,...
293,294,22,Aman,40,10000.0,Delhi,aman28@gmail.com,2023-04-20
296,297,88,Anjali,54,39808.0,Delhi,anjali43@gmail.com,2023-04-20
297,298,121,Simran,40,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,299,298,Rohit,40,10000.0,Mumbai,rohit11@gmail.com,2023-02-15
299,300,299,Aman,40,10000.0,Kolkata,aman17@gmail.com,2023-01-15

In [78]:
# Above data is almost cleaned 
# todo : clean df_missing_city

In [79]:
df_missing_city

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.0,NaN,riya48@gmail.com,2023/04/20
1,2,139,rohit,32,10000.0,NaN,rohit42@gmail.com,15/02/2023
6,7,6,Raj,40,10000.0,NaN,raj21@gmail.com,2023-01-15
11,12,11,Aman,40,86542.0,NaN,aman20@gmail.com,15/02/2023
14,15,102,Anjali,40,10000.0,NaN,anjali20@gmail.com,NaN
18,19,18,Priya,21,10000.0,NaN,priya22@gmail.com,15/02/2023
26,27,34,Karan,59,10000.0,NaN,karan7@gmail.com,2023-01-15
33,34,33,Karan,40,10000.0,NaN,karan35@gmail.com,2023-01-15
36,37,129,rohit,40,106951.0,NaN,rohit20@gmail.com,NaN
37,38,44,Priya,40,10000.0,NaN,priya48@gmail.com,NaN
39,40,39,riya,40,10000.0,NaN,riya20@gmail.com,15/02/2023
40,41,49,aman,57,10000.0,NaN,aman37@gmail.com,NaN
43,44,133,Anjali,40,10000.0,NaN,anjali18@gmail.com,15/02/2023
47,48,47,Simran,49,10000.0,NaN,simran44@gmail.com,NaN
53,54,17,Riya,40,10000.0,NaN,riya24@gmail.com,2023-01-15
71,72,73,Priya,40,10000.0,NaN,priya32@gmail.com,2023/04/20
72,73,118,Aman,38,72976.0,NaN,aman35@gmail.com,2023-01-15
82,83,82,Simran,24,10000.0,NaN,simran20@gmail.com,March 10 2023
88,89,10,priya,40,102345.0,NaN,priya42@gmail.com,NaN
95,96,55,Raj,40,56666.0,NaN,raj24@gmail.com,NaN
101,102,125,Karan,40,10000.0,NaN,karan7@gmail.com,2023-01-15
104,105,104,Rohit,40,10000.0,NaN,rohit31@gmail.com,2023-01-15
115,116,22,karan,40,10000.0,NaN,karan24@gmail.com,2023-01-15
123,124,123,Raj,40,64350.0,NaN,raj42@gmail.com,March 10 2023
125,126,125,rohit,40,10000.0,NaN,rohit22@gmail.com,NaN
137,138,137,Aman,40,10000.0,NaN,aman2@gmail.com,March 10 2023
140,141,73,Karan,40,53202.0,NaN,karan13@gmail.com,2023-01-15
149,150,140,Raj,40,10000.0,NaN,raj5@gmail.com,March 10 2023
154,155,154,Priya,36,10000.0,NaN,priya36@gmail.com,March 10 2023
156,157,156,Karan,44,10000.0,NaN,karan20@gmail.com,NaN
170,171,67,Rohit,40,10000.0,NaN,rohit50@gmail.com,15/02/2023
171,172,125,simran,40,10000.0,NaN,simran46@gmail.com,NaN
174,175,174,karan,40,51779.0,NaN,karan34@gmail.com,2023-01-15
181,182,181,Anjali,37,10000.0,NaN,anjali16@gmail.com,NaN
185,186,185,raj,46,10000.0,NaN,raj38@gmail.com,2023/04/20
189,190,189,Raj,40,10000.0,NaN,raj15@gmail.com,March 10 2023
193,194,56,Priya,40,10000.0,NaN,priya34@gmail.com,March 10 2023
198,199,198,Simran,40,44906.0,NaN,simran49@gmail.com,2023/04/20
223,224,223,Aman,52,10000.0,NaN,aman43@gmail.com,2023/04/20
229,230,50,Rohit,40,71849.0,NaN,rohit40@gmail.com,2023/04/20
243,244,117,Karan,40,62898.0,NaN,karan6@gmail.com,2023-01-15
247,248,59,Priya,40,10000.0,NaN,priya45@gmail.com,2023-01-15
250,251,38,raj,40,10000.0,NaN,raj14@gmail.com,2023/04/20
252,253,252,Priya,59,10000.0,NaN,priya2@gmail.com,2023/04/20
257,258,257,Priya,59,10000.0,NaN,priya16@gmail.com,2023-01-15
259,260,259,Anjali,40,10000.0,NaN,anjali50@gmail.com,2023-01-15
272,273,272,priya,40,87300.0,NaN,priya20@gmail.com,2023-01-15
291,292,291,rohit,40,10000.0,NaN,rohit2@gmail.com,2023/04/20
292,293,292,rohit,40,10000.0,NaN,rohit19@gmail.com,2023-01-15

In [80]:
### Creating a function in which by entering a serial no the user can add their city

In [83]:
def missing_city():
    inputSerialNo = int(input("Enter serial no. "))
    inputCity = input("Enter city name")
    func = ((df_missing_city['Unique_id']==inputSerialNo) & (df_missing_city['City'].isna()))
    if func.any():
        df_missing_city.loc[func,'City'] = inputCity
        print("City added successfully")
    else:
        print("City already exists or invalid serial no")
missing_city()

Enter serial no.  7
Enter city name Mohali

City added successfully

In [84]:
df_missing_city

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.0,NaN,riya48@gmail.com,2023/04/20
1,2,139,rohit,32,10000.0,Una,rohit42@gmail.com,15/02/2023
6,7,6,Raj,40,10000.0,Mohali,raj21@gmail.com,2023-01-15
11,12,11,Aman,40,86542.0,NaN,aman20@gmail.com,15/02/2023
14,15,102,Anjali,40,10000.0,NaN,anjali20@gmail.com,NaN
18,19,18,Priya,21,10000.0,NaN,priya22@gmail.com,15/02/2023
26,27,34,Karan,59,10000.0,NaN,karan7@gmail.com,2023-01-15
33,34,33,Karan,40,10000.0,NaN,karan35@gmail.com,2023-01-15
36,37,129,rohit,40,106951.0,NaN,rohit20@gmail.com,NaN
37,38,44,Priya,40,10000.0,NaN,priya48@gmail.com,NaN
39,40,39,riya,40,10000.0,NaN,riya20@gmail.com,15/02/2023
40,41,49,aman,57,10000.0,NaN,aman37@gmail.com,NaN
43,44,133,Anjali,40,10000.0,NaN,anjali18@gmail.com,15/02/2023
47,48,47,Simran,49,10000.0,NaN,simran44@gmail.com,NaN
53,54,17,Riya,40,10000.0,NaN,riya24@gmail.com,2023-01-15
71,72,73,Priya,40,10000.0,NaN,priya32@gmail.com,2023/04/20
72,73,118,Aman,38,72976.0,NaN,aman35@gmail.com,2023-01-15
82,83,82,Simran,24,10000.0,NaN,simran20@gmail.com,March 10 2023
88,89,10,priya,40,102345.0,NaN,priya42@gmail.com,NaN
95,96,55,Raj,40,56666.0,NaN,raj24@gmail.com,NaN
101,102,125,Karan,40,10000.0,NaN,karan7@gmail.com,2023-01-15
104,105,104,Rohit,40,10000.0,NaN,rohit31@gmail.com,2023-01-15
115,116,22,karan,40,10000.0,NaN,karan24@gmail.com,2023-01-15
123,124,123,Raj,40,64350.0,NaN,raj42@gmail.com,March 10 2023
125,126,125,rohit,40,10000.0,NaN,rohit22@gmail.com,NaN
137,138,137,Aman,40,10000.0,NaN,aman2@gmail.com,March 10 2023
140,141,73,Karan,40,53202.0,NaN,karan13@gmail.com,2023-01-15
149,150,140,Raj,40,10000.0,NaN,raj5@gmail.com,March 10 2023
154,155,154,Priya,36,10000.0,NaN,priya36@gmail.com,March 10 2023
156,157,156,Karan,44,10000.0,NaN,karan20@gmail.com,NaN
170,171,67,Rohit,40,10000.0,NaN,rohit50@gmail.com,15/02/2023
171,172,125,simran,40,10000.0,NaN,simran46@gmail.com,NaN
174,175,174,karan,40,51779.0,NaN,karan34@gmail.com,2023-01-15
181,182,181,Anjali,37,10000.0,NaN,anjali16@gmail.com,NaN
185,186,185,raj,46,10000.0,NaN,raj38@gmail.com,2023/04/20
189,190,189,Raj,40,10000.0,NaN,raj15@gmail.com,March 10 2023
193,194,56,Priya,40,10000.0,NaN,priya34@gmail.com,March 10 2023
198,199,198,Simran,40,44906.0,NaN,simran49@gmail.com,2023/04/20
223,224,223,Aman,52,10000.0,NaN,aman43@gmail.com,2023/04/20
229,230,50,Rohit,40,71849.0,NaN,rohit40@gmail.com,2023/04/20
243,244,117,Karan,40,62898.0,NaN,karan6@gmail.com,2023-01-15
247,248,59,Priya,40,10000.0,NaN,priya45@gmail.com,2023-01-15
250,251,38,raj,40,10000.0,NaN,raj14@gmail.com,2023/04/20
252,253,252,Priya,59,10000.0,NaN,priya2@gmail.com,2023/04/20
257,258,257,Priya,59,10000.0,NaN,priya16@gmail.com,2023-01-15
259,260,259,Anjali,40,10000.0,NaN,anjali50@gmail.com,2023-01-15
272,273,272,priya,40,87300.0,NaN,priya20@gmail.com,2023-01-15
291,292,291,rohit,40,10000.0,NaN,rohit2@gmail.com,2023/04/20
292,293,292,rohit,40,10000.0,NaN,rohit19@gmail.com,2023-01-15

In [85]:
# Through this function the cities can be updated and we can later add this data to our orignal dataset
# Now we are going to set date for this data

In [89]:
df_missing_city['JoiningDate']=pd.to_datetime(df_missing_city["JoiningDate"],format='mixed',dayfirst=True)

In [90]:
df_missing_city

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.0,NaN,riya48@gmail.com,2023-04-20
1,2,139,rohit,32,10000.0,Una,rohit42@gmail.com,2023-02-15
6,7,6,Raj,40,10000.0,Mohali,raj21@gmail.com,2023-01-15
11,12,11,Aman,40,86542.0,NaN,aman20@gmail.com,2023-02-15
14,15,102,Anjali,40,10000.0,NaN,anjali20@gmail.com,NaT
18,19,18,Priya,21,10000.0,NaN,priya22@gmail.com,2023-02-15
26,27,34,Karan,59,10000.0,NaN,karan7@gmail.com,2023-01-15
33,34,33,Karan,40,10000.0,NaN,karan35@gmail.com,2023-01-15
36,37,129,rohit,40,106951.0,NaN,rohit20@gmail.com,NaT
37,38,44,Priya,40,10000.0,NaN,priya48@gmail.com,NaT
39,40,39,riya,40,10000.0,NaN,riya20@gmail.com,2023-02-15
40,41,49,aman,57,10000.0,NaN,aman37@gmail.com,NaT
43,44,133,Anjali,40,10000.0,NaN,anjali18@gmail.com,2023-02-15
47,48,47,Simran,49,10000.0,NaN,simran44@gmail.com,NaT
53,54,17,Riya,40,10000.0,NaN,riya24@gmail.com,2023-01-15
71,72,73,Priya,40,10000.0,NaN,priya32@gmail.com,2023-04-20
72,73,118,Aman,38,72976.0,NaN,aman35@gmail.com,2023-01-15
82,83,82,Simran,24,10000.0,NaN,simran20@gmail.com,2023-03-10
88,89,10,priya,40,102345.0,NaN,priya42@gmail.com,NaT
95,96,55,Raj,40,56666.0,NaN,raj24@gmail.com,NaT
101,102,125,Karan,40,10000.0,NaN,karan7@gmail.com,2023-01-15
104,105,104,Rohit,40,10000.0,NaN,rohit31@gmail.com,2023-01-15
115,116,22,karan,40,10000.0,NaN,karan24@gmail.com,2023-01-15
123,124,123,Raj,40,64350.0,NaN,raj42@gmail.com,2023-03-10
125,126,125,rohit,40,10000.0,NaN,rohit22@gmail.com,NaT
137,138,137,Aman,40,10000.0,NaN,aman2@gmail.com,2023-03-10
140,141,73,Karan,40,53202.0,NaN,karan13@gmail.com,2023-01-15
149,150,140,Raj,40,10000.0,NaN,raj5@gmail.com,2023-03-10
154,155,154,Priya,36,10000.0,NaN,priya36@gmail.com,2023-03-10
156,157,156,Karan,44,10000.0,NaN,karan20@gmail.com,NaT
170,171,67,Rohit,40,10000.0,NaN,rohit50@gmail.com,2023-02-15
171,172,125,simran,40,10000.0,NaN,simran46@gmail.com,NaT
174,175,174,karan,40,51779.0,NaN,karan34@gmail.com,2023-01-15
181,182,181,Anjali,37,10000.0,NaN,anjali16@gmail.com,NaT
185,186,185,raj,46,10000.0,NaN,raj38@gmail.com,2023-04-20
189,190,189,Raj,40,10000.0,NaN,raj15@gmail.com,2023-03-10
193,194,56,Priya,40,10000.0,NaN,priya34@gmail.com,2023-03-10
198,199,198,Simran,40,44906.0,NaN,simran49@gmail.com,2023-04-20
223,224,223,Aman,52,10000.0,NaN,aman43@gmail.com,2023-04-20
229,230,50,Rohit,40,71849.0,NaN,rohit40@gmail.com,2023-04-20
243,244,117,Karan,40,62898.0,NaN,karan6@gmail.com,2023-01-15
247,248,59,Priya,40,10000.0,NaN,priya45@gmail.com,2023-01-15
250,251,38,raj,40,10000.0,NaN,raj14@gmail.com,2023-04-20
252,253,252,Priya,59,10000.0,NaN,priya2@gmail.com,2023-04-20
257,258,257,Priya,59,10000.0,NaN,priya16@gmail.com,2023-01-15
259,260,259,Anjali,40,10000.0,NaN,anjali50@gmail.com,2023-01-15
272,273,272,priya,40,87300.0,NaN,priya20@gmail.com,2023-01-15
291,292,291,rohit,40,10000.0,NaN,rohit2@gmail.com,2023-04-20
292,293,292,rohit,40,10000.0,NaN,rohit19@gmail.com,2023-01-15

In [92]:
df_missing_city.dropna(subset='JoiningDate',inplace=True)

In [93]:
df_missing_city

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.0,NaN,riya48@gmail.com,2023-04-20
1,2,139,rohit,32,10000.0,Una,rohit42@gmail.com,2023-02-15
6,7,6,Raj,40,10000.0,Mohali,raj21@gmail.com,2023-01-15
11,12,11,Aman,40,86542.0,NaN,aman20@gmail.com,2023-02-15
18,19,18,Priya,21,10000.0,NaN,priya22@gmail.com,2023-02-15
26,27,34,Karan,59,10000.0,NaN,karan7@gmail.com,2023-01-15
33,34,33,Karan,40,10000.0,NaN,karan35@gmail.com,2023-01-15
39,40,39,riya,40,10000.0,NaN,riya20@gmail.com,2023-02-15
43,44,133,Anjali,40,10000.0,NaN,anjali18@gmail.com,2023-02-15
53,54,17,Riya,40,10000.0,NaN,riya24@gmail.com,2023-01-15
71,72,73,Priya,40,10000.0,NaN,priya32@gmail.com,2023-04-20
72,73,118,Aman,38,72976.0,NaN,aman35@gmail.com,2023-01-15
82,83,82,Simran,24,10000.0,NaN,simran20@gmail.com,2023-03-10
101,102,125,Karan,40,10000.0,NaN,karan7@gmail.com,2023-01-15
104,105,104,Rohit,40,10000.0,NaN,rohit31@gmail.com,2023-01-15
115,116,22,karan,40,10000.0,NaN,karan24@gmail.com,2023-01-15
123,124,123,Raj,40,64350.0,NaN,raj42@gmail.com,2023-03-10
137,138,137,Aman,40,10000.0,NaN,aman2@gmail.com,2023-03-10
140,141,73,Karan,40,53202.0,NaN,karan13@gmail.com,2023-01-15
149,150,140,Raj,40,10000.0,NaN,raj5@gmail.com,2023-03-10
154,155,154,Priya,36,10000.0,NaN,priya36@gmail.com,2023-03-10
170,171,67,Rohit,40,10000.0,NaN,rohit50@gmail.com,2023-02-15
174,175,174,karan,40,51779.0,NaN,karan34@gmail.com,2023-01-15
185,186,185,raj,46,10000.0,NaN,raj38@gmail.com,2023-04-20
189,190,189,Raj,40,10000.0,NaN,raj15@gmail.com,2023-03-10
193,194,56,Priya,40,10000.0,NaN,priya34@gmail.com,2023-03-10
198,199,198,Simran,40,44906.0,NaN,simran49@gmail.com,2023-04-20
223,224,223,Aman,52,10000.0,NaN,aman43@gmail.com,2023-04-20
229,230,50,Rohit,40,71849.0,NaN,rohit40@gmail.com,2023-04-20
243,244,117,Karan,40,62898.0,NaN,karan6@gmail.com,2023-01-15
247,248,59,Priya,40,10000.0,NaN,priya45@gmail.com,2023-01-15
250,251,38,raj,40,10000.0,NaN,raj14@gmail.com,2023-04-20
252,253,252,Priya,59,10000.0,NaN,priya2@gmail.com,2023-04-20
257,258,257,Priya,59,10000.0,NaN,priya16@gmail.com,2023-01-15
259,260,259,Anjali,40,10000.0,NaN,anjali50@gmail.com,2023-01-15
272,273,272,priya,40,87300.0,NaN,priya20@gmail.com,2023-01-15
291,292,291,rohit,40,10000.0,NaN,rohit2@gmail.com,2023-04-20
292,293,292,rohit,40,10000.0,NaN,rohit19@gmail.com,2023-01-15

In [94]:
df.describe()

,Unique_id,CustomerID,Age,Salary,JoiningDate
count,196.000000,196.000000,196.000000,196.000000,196
mean,150.357143,109.923469,39.780612,24166.224490,2023-03-03 05:23:15.918367
min,3.000000,2.000000,22.000000,10000.000000,2023-01-15 00:00:00
25%,78.500000,43.750000,40.000000,10000.000000,2023-02-15 00:00:00
50%,152.500000,96.500000,40.000000,10000.000000,2023-03-10 00:00:00
75%,223.500000,144.000000,40.000000,10000.000000,2023-04-20 00:00:00
max,300.000000,299.000000,59.000000,119613.000000,2023-04-20 00:00:00
std,86.483821,78.704441,4.920687,30040.126146,NaN

In [95]:
# Now lets go back to our main data frame

In [96]:
df

,Unique_id,CustomerID,Name,Age,Salary,City,Email,JoiningDate
2,3,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,2023-03-10
3,4,3,Riya,40,10000.0,Kolkata,riya8@gmail.com,2023-04-20
4,5,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,6,5,Simran,40,10000.0,Chandigarh,simran14@gmail.com,2023-04-20
7,8,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,2023-03-10
...,...,...,...,...,...,...,...,...
293,294,22,Aman,40,10000.0,Delhi,aman28@gmail.com,2023-04-20
296,297,88,Anjali,54,39808.0,Delhi,anjali43@gmail.com,2023-04-20
297,298,121,Simran,40,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,299,298,Rohit,40,10000.0,Mumbai,rohit11@gmail.com,2023-02-15
299,300,299,Aman,40,10000.0,Kolkata,aman17@gmail.com,2023-01-15

In [101]:
df.rename(columns={'CustomerID':'Customer_id'},inplace=True)

In [102]:
df

,Unique_id,Customer_id,Name,Age,Salary,City,Email,JoiningDate
2,3,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,2023-03-10
3,4,3,Riya,40,10000.0,Kolkata,riya8@gmail.com,2023-04-20
4,5,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,6,5,Simran,40,10000.0,Chandigarh,simran14@gmail.com,2023-04-20
7,8,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,2023-03-10
...,...,...,...,...,...,...,...,...
293,294,22,Aman,40,10000.0,Delhi,aman28@gmail.com,2023-04-20
296,297,88,Anjali,54,39808.0,Delhi,anjali43@gmail.com,2023-04-20
297,298,121,Simran,40,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,299,298,Rohit,40,10000.0,Mumbai,rohit11@gmail.com,2023-02-15
299,300,299,Aman,40,10000.0,Kolkata,aman17@gmail.com,2023-01-15

In [103]:
df.rename(columns={"JoiningDate":"Joining_date"},inplace=True)

In [104]:
df

,Unique_id,Customer_id,Name,Age,Salary,City,Email,Joining_date
2,3,2,Anjali,40,10000.0,Chandigarh,anjali18@gmail.com,2023-03-10
3,4,3,Riya,40,10000.0,Kolkata,riya8@gmail.com,2023-04-20
4,5,58,Karan,40,112349.0,Delhi,karan43@gmail.com,2023-01-15
5,6,5,Simran,40,10000.0,Chandigarh,simran14@gmail.com,2023-04-20
7,8,7,Priya,40,10000.0,Bangalore,priya42@gmail.com,2023-03-10
...,...,...,...,...,...,...,...,...
293,294,22,Aman,40,10000.0,Delhi,aman28@gmail.com,2023-04-20
296,297,88,Anjali,54,39808.0,Delhi,anjali43@gmail.com,2023-04-20
297,298,121,Simran,40,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,299,298,Rohit,40,10000.0,Mumbai,rohit11@gmail.com,2023-02-15
299,300,299,Aman,40,10000.0,Kolkata,aman17@gmail.com,2023-01-15

In [107]:
df.info()

<class 'pandas.DataFrame'>
Index: 196 entries, 2 to 299
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unique_id     196 non-null    int64
 1   Customer_id   196 non-null    int64
 2   Name          196 non-null    str
 3   Age           196 non-null    int64
 4   Salary        196 non-null    float64
 5   City          196 non-null    str
 6   Email         196 non-null    str
 7   Joining_date  196 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 13.8 KB

In [109]:
df.isna().sum()

Unique_id       0
Customer_id     0
Name            0
Age             0
Salary          0
City            0
Email           0
Joining_date    0
dtype: int64

In [110]:
df.duplicated().sum()

np.int64(0)

In [106]:
# Now our data is filtered . Now its time to visulize